stages:
  - trigger

# ==========================================
# 1. PYTHON VOTE FRONTEND TRIGGER
# ==========================================
trigger-vote:
  stage: trigger
  trigger:
    include: vote/.gitlab-ci-vote.yml
    strategy: depend
  rules:
    - changes:
        - vote/**/*

# ==========================================
# 2. .NET WORKER BACKEND TRIGGER
# ==========================================
trigger-worker:
  stage: trigger
  trigger:
    include: worker/.gitlab-ci-worker.yml
    strategy: depend
  rules:
    - changes:
        - worker/**/*

# ==========================================
# 3. NODE.JS RESULT FRONTEND TRIGGER
# ==========================================
trigger-results:
  stage: trigger
  trigger:
    include: result/.gitlab-ci-results.yml
    strategy: depend
  rules:
    - changes:
        - result/**/*

# ==========================================
# 4. PYTHON SEED DATA TRIGGER
# ==========================================
trigger-seed:
  stage: trigger
  trigger:
    include: seed-data/.gitlab-ci-seed.yml
    strategy: depend
  rules:
    - changes:
        - seed-data/**/*

# ==========================================
