apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: voting-app
data:
  REDIS_HOST: "redis"
  DB_HOST: "db"
  POSTGRES_DB: "postgres"

---
#Note: In a real production environment, you should use AWS Secrets Manager or HashiCorp Vault.
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: voting-app
type: Opaque
data:
  # Base64 encoded 'postgres'
  POSTGRES_USER: cG9zdGdyZXM= 
  POSTGRES_PASSWORD: cG9zdGdyZXM=