apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: voting-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3 # Uses the AWS EBS CSI driver to provision a disk
  resources:
    requests:
      storage: 4Gi