apiVersion: batch/v1
kind: Job
metadata:
  name: seed-data-job
  namespace: voting-app
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: seed-data
          image: ram7800/seed-data:18aad9df
          imagePullPolicy: Always
          env:
            # Load from ConfigMap
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_HOST
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            # Load from Secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
      restartPolicy: OnFailure